import type { Metadata } from 'next'
import '../styles/globals.css'
import { Lora } from 'next/font/google'
import Footer from '@/components/footer'
import Header from '@/components/header'

export const metadata: Metadata = {
  title: 'Pages Transition with Motion',
  description: 'Generated by create next app',
}

const lora = Lora({
  weight: ['400', '500'],
  variable: '--font-lora',
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={lora.className}>
      <body>
        <Header />
        {children}

        <Footer />
      </body>
    </html>
  )
}
